/* ============================================================
   EngForDev 数据层 data.js
   - 章节内容（ch1 自我介绍 / ch2 数字与时间 / ch3 问路与方向）
   - 占位后续章节 ch4 / ch5（锁定，演示解锁逻辑）
   - 徽章定义（打卡 / 跟读 / 角色扮演 / 完成 A1 等）
   - 内置词典（约 500 个计算机高频词，字幕点词弹释义）
   暴露在 window.ENG_DATA 上，供 app.js 与 test.html 使用
   ============================================================ */
(function () {
  'use strict';

  // ---------- 章节数据 ----------
  const CHAPTERS = [
    {
      id: 'ch1',
      title: '自我介绍',
      emoji: '👋',
      goal: '学会用英语做一段完整、得体的自我介绍',
      blocks: [
        { en: "I am a developer.",           zh: "我是一名开发者。",         speak: "I am a developer." },
        { en: "My name is Alex.",            zh: "我叫 Alex。",             speak: "My name is Alex." },
        { en: "I'm from Shanghai.",          zh: "我来自上海。",            speak: "I'm from Shanghai." },
        { en: "Nice to meet you.",           zh: "很高兴认识你。",          speak: "Nice to meet you." },
        { en: "I work as an engineer.",      zh: "我是一名工程师。",        speak: "I work as an engineer." },
        { en: "I'm responsible for the UI.", zh: "我负责用户界面。",         speak: "I'm responsible for the UI." },
        { en: "I have three years of experience.", zh: "我有三年工作经验。", speak: "I have three years of experience." },
        { en: "I am good at JavaScript.",    zh: "我擅长 JavaScript。",     speak: "I am good at JavaScript." },
        { en: "I enjoy solving problems.",   zh: "我喜欢解决问题。",         speak: "I enjoy solving problems." },
        { en: "I'm a team player.",          zh: "我有团队合作精神。",       speak: "I'm a team player." },
        { en: "I graduated from Peking University.", zh: "我毕业于北京大学。", speak: "I graduated from Peking University." },
        { en: "Thank you for your time.",    zh: "感谢您的时间。",           speak: "Thank you for your time." }
      ],
      grammar: {
        title: 'be 动词与常用介词',
        rule: 'be 动词随主语变化：I am / you are / he(she) is / we(they) are；表示来自某地用 be from，负责某事用 be responsible for，擅长用 be good at。',
        table: [['主语', 'be 动词'], ['I', 'am'], ['he / she / it', 'is'], ['you / we / they', 'are']],
        examples: ['I am a developer.', 'She is a designer.', 'We are a team.']
      },
      // 16 道练习题：选择 4 / 填空 4 / 排序 2 / 翻译 3 / 复述 3
      quiz: [
        { id: 'q1',  type: 'choice', prompt: 'I ___ a developer.', options: ['am', 'is', 'are'], answer: 0, knowledge: 'be 动词' },
        { id: 'q2',  type: 'choice', prompt: 'She ___ a designer.', options: ['am', 'is', 'are'], answer: 1, knowledge: 'be 动词' },
        { id: 'q3',  type: 'choice', prompt: '自我介绍结尾常用：', options: ['Nice to meet you.', 'See you later.', "What's up?"], answer: 0, knowledge: '交际用语' },
        { id: 'q4',  type: 'choice', prompt: '"我有团队合作精神" 怎么说？', options: ["I'm a team player.", "I team player.", "I am team player."], answer: 0, knowledge: '交际用语' },
        { id: 'q5',  type: 'fill',   prompt: 'I ___ a frontend engineer.（填 be 动词）', answer: 'am', accept: ['am'], knowledge: 'be 动词' },
        { id: 'q6',  type: 'fill',   prompt: 'My name ___ Alex.（填 be 动词）', answer: 'is', accept: ['is'], knowledge: 'be 动词' },
        { id: 'q7',  type: 'fill',   prompt: 'I come ___ Shanghai.（填介词）', answer: 'from', accept: ['from'], knowledge: '介词 from' },
        { id: 'q8',  type: 'fill',   prompt: 'I enjoy ___ problems.（填 solve 的正确形式）', answer: 'solving', accept: ['solving'], knowledge: '动名词' },
        { id: 'q9',  type: 'order',  prompt: '排列成句', words: ['I', 'work', 'as', 'an', 'engineer'], answer: ['I', 'work', 'as', 'an', 'engineer'], knowledge: '句型 SVO' },
        { id: 'q10', type: 'order',  prompt: '排列成句', words: ['Nice', 'to', 'meet', 'you'], answer: ['Nice', 'to', 'meet', 'you'], knowledge: '交际用语' },
        { id: 'q11', type: 'translation', prompt: '中译英：我叫 Alex。', answer: 'My name is Alex', accept: ['My name is Alex', "My name's Alex"], knowledge: '自我介绍' },
        { id: 'q12', type: 'translation', prompt: '中译英：很高兴认识你。', answer: 'Nice to meet you', accept: ['Nice to meet you'], knowledge: '交际用语' },
        { id: 'q13', type: 'translation', prompt: '中译英：我来自上海。', answer: 'I am from Shanghai', accept: ['I am from Shanghai', "I'm from Shanghai"], knowledge: '介词 from' },
        { id: 'q14', type: 'retell', prompt: 'I am a frontend engineer from Shanghai.', keywords: ['frontend', 'engineer', 'Shanghai'], knowledge: '自我介绍' },
        { id: 'q15', type: 'retell', prompt: 'I have three years of experience.', keywords: ['three', 'years', 'experience'], knowledge: '工作经验' },
        { id: 'q16', type: 'retell', prompt: 'I am good at JavaScript.', keywords: ['good', 'javascript'], knowledge: '技能表达' }
      ],
      video: {
        title: '自我介绍对话',
        poster: '👋',
        cues: [
          { t: 0,  en: "Hi, I'm Alex.",                     zh: '嗨，我是 Alex。' },
          { t: 3,  en: "Nice to meet you.",                  zh: '很高兴认识你。' },
          { t: 6,  en: "I'm from Shanghai.",                 zh: '我来自上海。' },
          { t: 9,  en: "I work as an engineer.",             zh: '我是一名工程师。' },
          { t: 12, en: "I'm responsible for the UI.",        zh: '我负责用户界面。' },
          { t: 15, en: "I have three years of experience.",  zh: '我有三年工作经验。' },
          { t: 18, en: "I am good at JavaScript.",           zh: '我擅长 JavaScript。' },
          { t: 21, en: "I enjoy solving problems.",          zh: '我喜欢解决问题。' },
          { t: 24, en: "I'm a team player.",                 zh: '我有团队合作精神。' },
          { t: 27, en: "I graduated from Peking University.",zh: '我毕业于北京大学。' },
          { t: 30, en: "Thank you for your time.",           zh: '感谢您的时间。' },
          { t: 33, en: "See you later!",                     zh: '回头见！' }
        ]
      },
      // 角色扮演：2 个场景，每个 9 轮开口对话
      roleplay: {
        scene: '选择场景：A 向新同事自我介绍，B 向面试官自我介绍。',
        start: 'r0',
        nodes: {
          r0: {
            npc: "Hi! I'm Jamie, a new colleague. Which scenario do you want to practice?",
            options: [
              { text: "A. Introduce to a new colleague", next: 'a1' },
              { text: "B. Introduce to an interviewer",  next: 'b1' }
            ]
          },
          a1: { npc: "Hi there! What's your name?",           expected: "My name is Alex.",               next: 'a2' },
          a2: { npc: "Nice to meet you, Alex. Where are you from?", expected: "I am from Shanghai.",      next: 'a3' },
          a3: { npc: "What do you do here?",                    expected: "I work as an engineer.",         next: 'a4' },
          a4: { npc: "Cool! What are you responsible for?",     expected: "I am responsible for the UI.",   next: 'a5' },
          a5: { npc: "How long have you been doing this?",      expected: "I have three years of experience.", next: 'a6' },
          a6: { npc: "What are you good at?",                   expected: "I am good at JavaScript.",       next: 'a7' },
          a7: { npc: "Do you like working in a team?",          expected: "Yes, I am a team player.",       next: 'a8' },
          a8: { npc: "What do you enjoy doing?",                expected: "I enjoy solving problems.",      next: 'a9' },
          a9: { npc: "Great to meet you, Alex!",                expected: "Nice to meet you too.",          next: 'aend' },
          aend: { npc: "Welcome to the team! 🎉", end: true },
          b1: { npc: "Good morning. Please introduce yourself.", expected: "My name is Alex.",               next: 'b2' },
          b2: { npc: "Where did you graduate from?",             expected: "I graduated from Peking University.", next: 'b3' },
          b3: { npc: "What is your current role?",               expected: "I work as an engineer.",         next: 'b4' },
          b4: { npc: "What are you responsible for?",            expected: "I am responsible for the UI.",   next: 'b5' },
          b5: { npc: "How much experience do you have?",         expected: "I have three years of experience.", next: 'b6' },
          b6: { npc: "What skills do you have?",                 expected: "I am good at JavaScript.",       next: 'b7' },
          b7: { npc: "Do you enjoy solving problems?",           expected: "Yes, I enjoy solving problems.", next: 'b8' },
          b8: { npc: "Are you a team player?",                   expected: "Yes, I am a team player.",       next: 'b9' },
          b9: { npc: "Do you have any questions for us?",        expected: "Thank you for your time.",       next: 'bend' },
          bend: { npc: "Thank you for your time! 🎉", end: true }
        }
      },
      // 16 道章测题：与练习题无完全重复，覆盖全部知识点
      exam: [
        { id: 'e1',  type: 'choice', prompt: 'They ___ developers.', options: ['am', 'is', 'are'], answer: 2, knowledge: 'be 动词' },
        { id: 'e2',  type: 'choice', prompt: 'He ___ a QA engineer.', options: ['am', 'is', 'are'], answer: 1, knowledge: 'be 动词' },
        { id: 'e3',  type: 'choice', prompt: '"我擅长编程" 怎么说？', options: ['I am good at programming.', 'I good at programming.', 'I am good programming.'], answer: 0, knowledge: '技能表达' },
        { id: 'e4',  type: 'choice', prompt: '"再见" 怎么说？', options: ['See you later.', 'Nice to meet you.', 'Thank you.'], answer: 0, knowledge: '交际用语' },
        { id: 'e5',  type: 'fill',   prompt: 'She ___ a designer.（填 be 动词）', answer: 'is', accept: ['is'], knowledge: 'be 动词' },
        { id: 'e6',  type: 'fill',   prompt: 'They ___ from Beijing.（填 be 动词）', answer: 'are', accept: ['are'], knowledge: 'be 动词' },
        { id: 'e7',  type: 'fill',   prompt: 'She graduated ___ Peking University.（填介词）', answer: 'from', accept: ['from'], knowledge: '介词 from' },
        { id: 'e8',  type: 'fill',   prompt: 'I am good ___ JavaScript.（填介词）', answer: 'at', accept: ['at'], knowledge: '介词 at' },
        { id: 'e9',  type: 'order',  prompt: '排列成句', words: ['I', 'graduated', 'from', 'Peking', 'University'], answer: ['I', 'graduated', 'from', 'Peking', 'University'], knowledge: '句型 SVO' },
        { id: 'e10', type: 'order',  prompt: '排列成句', words: ['I', 'have', 'three', 'years', 'of', 'experience'], answer: ['I', 'have', 'three', 'years', 'of', 'experience'], knowledge: '工作经验' },
        { id: 'e11', type: 'translation', prompt: '中译英：他是一名测试工程师。', answer: 'He is a QA engineer', accept: ['He is a QA engineer'], knowledge: 'be 动词' },
        { id: 'e12', type: 'translation', prompt: '中译英：我们是一个团队。', answer: 'We are a team', accept: ['We are a team'], knowledge: 'be 动词' },
        { id: 'e13', type: 'translation', prompt: '中译英：感谢您的时间。', answer: 'Thank you for your time', accept: ['Thank you for your time'], knowledge: '交际用语' },
        { id: 'e14', type: 'retell', prompt: 'She works as a designer at our company.', keywords: ['designer', 'company'], knowledge: '工作角色' },
        { id: 'e15', type: 'retell', prompt: 'I enjoy solving problems every day.', keywords: ['enjoy', 'solving', 'problems'], knowledge: '动名词' },
        { id: 'e16', type: 'retell', prompt: 'We work together as a team.', keywords: ['work', 'team'], knowledge: '团队合作' }
      ],
      xp: 90
    },

    // ---------- 第二章：数字与时间 ----------
    {
      id: 'ch2',
      title: '数字与时间',
      emoji: '🔢',
      goal: '学会用英语表达数字、时刻与时间安排，能讨论工作量与日程',
      blocks: [
        { en: "It's ten o'clock.",                  zh: "现在是十点。",       speak: "It's ten o'clock." },
        { en: "The meeting starts at nine AM.",     zh: "会议九点开始。",     speak: "The meeting starts at nine AM." },
        { en: "I have three tasks today.",          zh: "我今天有三个任务。", speak: "I have three tasks today." },
        { en: "The bug was fixed in five minutes.", zh: "这个 bug 五分钟就修好了。", speak: "The bug was fixed in five minutes." },
        { en: "Please wait a second.",              zh: "请稍等一下。",       speak: "Please wait a second." },
        { en: "It's half past two.",                zh: "现在两点半。",       speak: "It's half past two." },
        { en: "The deadline is tomorrow.",          zh: "截止日期是明天。",   speak: "The deadline is tomorrow." },
        { en: "I work from nine to six.",           zh: "我从九点工作到六点。", speak: "I work from nine to six." },
        { en: "Let's meet at 10:30.",               zh: "我们十点半见面吧。", speak: "Let's meet at 10:30." },
        { en: "It takes twenty minutes.",           zh: "需要二十分钟。",     speak: "It takes twenty minutes." },
        { en: "See you on Monday.",                 zh: "周一见。",           speak: "See you on Monday." },
        { en: "I'll be there in an hour.",          zh: "我一小时后到。",     speak: "I'll be there in an hour." }
      ],
      grammar: {
        title: '数词、时刻与时间介词',
        rule: '基数词表数量；序数词表顺序；时刻用 at + 时间；"是几点"用 It\'s ...；星期用 on。',
        table: [['类型', '示例'], ['基数词', 'one, two, three, ten, twenty'], ['序数词', 'first, second, third'], ['时刻介词', 'at nine, at 10:30'], ['星期介词', 'on Monday']],
        examples: ["It's ten o'clock.", 'The meeting starts at nine AM.', 'I have three tasks today.']
      },
      // 16 道练习题：选择 4 / 填空 4 / 排序 2 / 翻译 3 / 复述 3
      quiz: [
        { id: 'q1',  type: 'choice', prompt: "It's ___ o'clock.（10点）", options: ['ten', 'tenth', 'tenly'], answer: 0, knowledge: '数词' },
        { id: 'q2',  type: 'choice', prompt: 'The meeting starts ___ nine AM.', options: ['at', 'in', 'on'], answer: 0, knowledge: '介词 at' },
        { id: 'q3',  type: 'choice', prompt: '"请稍等" 怎么说？', options: ['Please wait a second.', 'Please wait second.', 'Wait second please.'], answer: 0, knowledge: '交际用语' },
        { id: 'q4',  type: 'choice', prompt: 'See you ___ Monday.', options: ['on', 'in', 'at'], answer: 0, knowledge: '介词 on' },
        { id: 'q5',  type: 'fill',   prompt: 'The bug was fixed in five ___.（填"分钟"）', answer: 'minutes', accept: ['minutes', 'minute'], knowledge: '时间单位' },
        { id: 'q6',  type: 'fill',   prompt: "It's half ___ two.（填「过」）", answer: 'past', accept: ['past'], knowledge: '时刻表达' },
        { id: 'q7',  type: 'fill',   prompt: 'The deadline is ___.（填「明天」）', answer: 'tomorrow', accept: ['tomorrow'], knowledge: '时间词' },
        { id: 'q8',  type: 'fill',   prompt: "I'll be there in an ___.（填「小时」）", answer: 'hour', accept: ['hour'], knowledge: '时间单位' },
        { id: 'q9',  type: 'order',  prompt: '排列成句', words: ['I', 'have', 'three', 'tasks', 'today'], answer: ['I', 'have', 'three', 'tasks', 'today'], knowledge: '句型 SVO' },
        { id: 'q10', type: 'order',  prompt: '排列成句', words: ['The', 'meeting', 'starts', 'at', 'nine'], answer: ['The', 'meeting', 'starts', 'at', 'nine'], knowledge: '时刻表达' },
        { id: 'q11', type: 'translation', prompt: '中译英：现在是十点。', answer: "It's ten o'clock", accept: ["It's ten o'clock"], knowledge: '时刻表达' },
        { id: 'q12', type: 'translation', prompt: '中译英：我今天有三个任务。', answer: 'I have three tasks today', accept: ['I have three tasks today'], knowledge: '数词' },
        { id: 'q13', type: 'translation', prompt: '中译英：请稍等一下。', answer: 'Please wait a second', accept: ['Please wait a second'], knowledge: '交际用语' },
        { id: 'q14', type: 'retell', prompt: 'The meeting starts at nine AM.', keywords: ['meeting', 'starts', 'nine'], knowledge: '时刻表达' },
        { id: 'q15', type: 'retell', prompt: 'I work from nine to six.', keywords: ['work', 'nine', 'six'], knowledge: '工作时间' },
        { id: 'q16', type: 'retell', prompt: "It takes twenty minutes.", keywords: ['takes', 'twenty', 'minutes'], knowledge: '时间单位' }
      ],
      video: {
        title: '团队站会：今日时间安排',
        poster: '⏰',
        cues: [
          { t: 0,  en: "Good morning, team.",                zh: '早上好，团队。' },
          { t: 3,  en: "It's ten o'clock now.",              zh: '现在是十点。' },
          { t: 6,  en: "The stand-up starts at nine AM.",    zh: '站会九点开始。' },
          { t: 9,  en: "I have three tasks today.",           zh: '我今天有三个任务。' },
          { t: 12, en: "The deadline is tomorrow.",           zh: '截止日期是明天。' },
          { t: 15, en: "It's half past two.",                zh: '现在两点半。' },
          { t: 18, en: "Let's finish in five minutes.",      zh: '我们五分钟内结束吧。' },
          { t: 21, en: "I work from nine to six.",            zh: '我从九点工作到六点。' },
          { t: 24, en: "See you on Monday.",                 zh: '周一见。' },
          { t: 27, en: "Please wait a second.",              zh: '请稍等一下。' },
          { t: 30, en: "I'll be there in an hour.",           zh: '我一小时后到。' },
          { t: 33, en: "It takes twenty minutes.",            zh: '需要二十分钟。' }
        ]
      },
      // 角色扮演：2 个场景，每个 9 轮开口
      roleplay: {
        scene: '选择场景：A 确认会议日程，B 估算任务时间。',
        start: 'r0',
        nodes: {
          r0: {
            npc: "Hi! Let's talk about time. Which scenario do you prefer?",
            options: [
              { text: "A. Meeting schedule.",     next: 'a1' },
              { text: "B. Task time estimate.",   next: 'b1' }
            ]
          },
          a1: { npc: "What time does the stand-up start?",   expected: "It starts at nine AM.",            next: 'a2' },
          a2: { npc: "What time is it now?",                  expected: "It's ten o'clock.",                next: 'a3' },
          a3: { npc: "When is the deadline?",                 expected: "The deadline is tomorrow.",        next: 'a4' },
          a4: { npc: "What time should we meet?",             expected: "Let's meet at 10:30.",             next: 'a5' },
          a5: { npc: "Which day?",                            expected: "See you on Monday.",               next: 'a6' },
          a6: { npc: "What are your working hours?",          expected: "I work from nine to six.",         next: 'a7' },
          a7: { npc: "How long will you be there?",           expected: "I'll be there in an hour.",        next: 'a8' },
          a8: { npc: "Can you come at half past two?",        expected: "Yes, it's half past two.",         next: 'a9' },
          a9: { npc: "Great, see you then!",                  expected: "See you on Monday.",               next: 'aend' },
          aend: { npc: "Perfect! See you at the meeting 🎉", end: true },
          b1: { npc: "How many tasks do you have today?",     expected: "I have three tasks today.",        next: 'b2' },
          b2: { npc: "How long does it take to fix the bug?", expected: "It takes twenty minutes.",         next: 'b3' },
          b3: { npc: "When was the bug fixed?",               expected: "The bug was fixed in five minutes.", next: 'b4' },
          b4: { npc: "What time is it now?",                  expected: "It's half past two.",              next: 'b5' },
          b5: { npc: "Can we finish quickly?",                expected: "Please wait a second.",            next: 'b6' },
          b6: { npc: "When is the deadline?",                 expected: "The deadline is tomorrow.",        next: 'b7' },
          b7: { npc: "Will you finish on time?",              expected: "Yes, I'll be there in an hour.",   next: 'b8' },
          b8: { npc: "How many minutes do you need?",         expected: "It takes twenty minutes.",         next: 'b9' },
          b9: { npc: "Great, let's get it done!",             expected: "See you on Monday.",               next: 'bend' },
          bend: { npc: "Well done! Let's finish on time 🎉", end: true }
        }
      },
      // 16 道章测题：与练习题无完全重复
      exam: [
        { id: 'e1',  type: 'choice', prompt: '"现在是十点" 怎么说？', options: ["It's ten o'clock.", "It ten o'clock.", "It's ten clock."], answer: 0, knowledge: '时刻表达' },
        { id: 'e2',  type: 'choice', prompt: 'I have ___ tasks today.（3个）', options: ['three', 'third', 'threely'], answer: 0, knowledge: '数词' },
        { id: 'e3',  type: 'choice', prompt: '"我们十点半见面" 怎么说？', options: ["Let's meet at 10:30.", "Let meet 10:30.", "Let's meet 10:30."], answer: 0, knowledge: '时刻表达' },
        { id: 'e4',  type: 'choice', prompt: '"会议九点开始" 怎么说？', options: ["The meeting starts at nine AM.", "The meeting start nine AM.", "The meeting starts nine AM."], answer: 0, knowledge: '介词 at' },
        { id: 'e5',  type: 'fill',   prompt: 'It takes twenty ___.（填「分钟」）', answer: 'minutes', accept: ['minutes', 'minute'], knowledge: '时间单位' },
        { id: 'e6',  type: 'fill',   prompt: 'I work ___ nine to six.（填介词）', answer: 'from', accept: ['from'], knowledge: '介词 from' },
        { id: 'e7',  type: 'fill',   prompt: "It's half ___ three.（填「过」）", answer: 'past', accept: ['past'], knowledge: '时刻表达' },
        { id: 'e8',  type: 'fill',   prompt: 'See you ___ Friday.（填介词）', answer: 'on', accept: ['on'], knowledge: '介词 on' },
        { id: 'e9',  type: 'order',  prompt: '排列成句', words: ['I', 'work', 'from', 'nine', 'to', 'six'], answer: ['I', 'work', 'from', 'nine', 'to', 'six'], knowledge: '工作时间' },
        { id: 'e10', type: 'order',  prompt: '排列成句', words: ['Please', 'wait', 'a', 'second'], answer: ['Please', 'wait', 'a', 'second'], knowledge: '交际用语' },
        { id: 'e11', type: 'translation', prompt: '中译英：截止日期是明天。', answer: 'The deadline is tomorrow', accept: ['The deadline is tomorrow'], knowledge: '时间词' },
        { id: 'e12', type: 'translation', prompt: '中译英：需要二十分钟。', answer: 'It takes twenty minutes', accept: ['It takes twenty minutes'], knowledge: '时间单位' },
        { id: 'e13', type: 'translation', prompt: '中译英：周一见。', answer: 'See you on Monday', accept: ['See you on Monday'], knowledge: '介词 on' },
        { id: 'e14', type: 'retell', prompt: 'I have three tasks today.', keywords: ['three', 'tasks', 'today'], knowledge: '数词' },
        { id: 'e15', type: 'retell', prompt: 'The deadline is tomorrow.', keywords: ['deadline', 'tomorrow'], knowledge: '时间词' },
        { id: 'e16', type: 'retell', prompt: "I'll be there in an hour.", keywords: ['there', 'hour'], knowledge: '时间单位' }
      ],
      xp: 100
    },

    // ---------- 第三章：问路与方向 ----------
    {
      id: 'ch3',
      title: '问路与方向',
      emoji: '🧭',
      goal: '学会用英语问路、指路，能在办公室或园区里描述位置与方向',
      blocks: [
        { en: "Where is the restroom?",          zh: "洗手间在哪里？",     speak: "Where is the restroom?" },
        { en: "Go straight ahead.",              zh: "一直往前走。",       speak: "Go straight ahead." },
        { en: "Turn left at the corner.",        zh: "在拐角左转。",       speak: "Turn left at the corner." },
        { en: "It's on your right.",             zh: "就在你右边。",       speak: "It's on your right." },
        { en: "How do I get to the office?",     zh: "我怎么去办公室？",   speak: "How do I get to the office?" },
        { en: "Excuse me.",                      zh: "打扰一下。",         speak: "Excuse me." },
        { en: "Turn right at the traffic light.", zh: "在红绿灯右转。",    speak: "Turn right at the traffic light." },
        { en: "It's next to the cafeteria.",     zh: "就在食堂旁边。",     speak: "It's next to the cafeteria." },
        { en: "Walk for two blocks.",            zh: "走两个街区。",       speak: "Walk for two blocks." },
        { en: "You can't miss it.",              zh: "你不会错过的。",     speak: "You can't miss it." },
        { en: "It's on the second floor.",       zh: "在二楼。",           speak: "It's on the second floor." },
        { en: "Thank you so much!",              zh: "太感谢了！",         speak: "Thank you so much!" }
      ],
      grammar: {
        title: '方位介词与祈使句',
        rule: '指路用祈使句 Go straight / Turn left / Turn right；表位置用 in/on/at + 地点；on your left / right 表示左右；next to 表示紧邻。',
        table: [['表达', '用法'], ['Go straight', '一直走'], ['Turn left / right', '左转 / 右转'], ['on your left / right', '在你左 / 右边'], ['next to', '紧邻'], ['at the corner', '在拐角处']],
        examples: ['Go straight ahead.', 'Turn left at the corner.', "It's on your right.", "It's next to the cafeteria."]
      },
      // 16 道练习题：选择 4 / 填空 4 / 排序 2 / 翻译 3 / 复述 3
      quiz: [
        { id: 'q1',  type: 'choice', prompt: '"洗手间在哪里" 怎么问？', options: ["Where is the restroom?", "Where restroom?", "Where is restroom?"], answer: 0, knowledge: '问路句型' },
        { id: 'q2',  type: 'choice', prompt: '"一直往前走" 怎么说？', options: ['Go straight ahead.', 'Go ahead straight.', 'Straight go ahead.'], answer: 0, knowledge: '祈使句' },
        { id: 'q3',  type: 'choice', prompt: '"打扰一下" 怎么说？', options: ['Excuse me.', 'Sorry me.', 'Pardon you.'], answer: 0, knowledge: '交际用语' },
        { id: 'q4',  type: 'choice', prompt: '"你不会错过的" 怎么说？', options: ["You can't miss it.", "You not miss it.", "You no miss it."], answer: 0, knowledge: '指路用语' },
        { id: 'q5',  type: 'fill',   prompt: 'Turn left ___ the corner.（填介词）', answer: 'at', accept: ['at'], knowledge: '介词 at' },
        { id: 'q6',  type: 'fill',   prompt: "It's on your ___.（填「右边」）", answer: 'right', accept: ['right'], knowledge: '方位词' },
        { id: 'q7',  type: 'fill',   prompt: 'Go ___ ahead.（填「一直」）', answer: 'straight', accept: ['straight'], knowledge: '祈使句' },
        { id: 'q8',  type: 'fill',   prompt: "It's next ___ the cafeteria.（填介词）", answer: 'to', accept: ['to'], knowledge: '介词 to' },
        { id: 'q9',  type: 'order',  prompt: '排列成句', words: ['Turn', 'left', 'at', 'the', 'corner'], answer: ['Turn', 'left', 'at', 'the', 'corner'], knowledge: '祈使句' },
        { id: 'q10', type: 'order',  prompt: '排列成句', words: ['How', 'do', 'I', 'get', 'to', 'the', 'office'], answer: ['How', 'do', 'I', 'get', 'to', 'the', 'office'], knowledge: '问路句型' },
        { id: 'q11', type: 'translation', prompt: '中译英：洗手间在哪里？', answer: 'Where is the restroom', accept: ['Where is the restroom', 'Where is the bathroom'], knowledge: '问路句型' },
        { id: 'q12', type: 'translation', prompt: '中译英：一直往前走。', answer: 'Go straight ahead', accept: ['Go straight ahead'], knowledge: '祈使句' },
        { id: 'q13', type: 'translation', prompt: '中译英：太感谢了！', answer: 'Thank you so much', accept: ['Thank you so much', 'Thanks a lot'], knowledge: '交际用语' },
        { id: 'q14', type: 'retell', prompt: 'Turn right at the traffic light.', keywords: ['turn', 'right', 'traffic', 'light'], knowledge: '祈使句' },
        { id: 'q15', type: 'retell', prompt: "It's next to the cafeteria.", keywords: ['next', 'cafeteria'], knowledge: '介词 to' },
        { id: 'q16', type: 'retell', prompt: "It's on the second floor.", keywords: ['second', 'floor'], knowledge: '方位词' }
      ],
      video: {
        title: '园区指路对话',
        poster: '🧭',
        cues: [
          { t: 0,  en: "Excuse me.",                          zh: '打扰一下。' },
          { t: 3,  en: "Where is the restroom?",              zh: '洗手间在哪里？' },
          { t: 6,  en: "Go straight ahead.",                  zh: '一直往前走。' },
          { t: 9,  en: "Turn left at the corner.",            zh: '在拐角左转。' },
          { t: 12, en: "It's on your right.",                 zh: '就在你右边。' },
          { t: 15, en: "It's next to the cafeteria.",         zh: '就在食堂旁边。' },
          { t: 18, en: "Walk for two blocks.",                zh: '走两个街区。' },
          { t: 21, en: "Turn right at the traffic light.",    zh: '在红绿灯右转。' },
          { t: 24, en: "It's on the second floor.",           zh: '在二楼。' },
          { t: 27, en: "You can't miss it.",                  zh: '你不会错过的。' },
          { t: 30, en: "How do I get to the office?",         zh: '我怎么去办公室？' },
          { t: 33, en: "Thank you so much!",                  zh: '太感谢了！' }
        ]
      },
      // 角色扮演：2 个场景，每个 9 轮开口
      roleplay: {
        scene: '选择场景：A 问洗手间在哪，B 问会议室在哪。',
        start: 'r0',
        nodes: {
          r0: {
            npc: "Hi! Need directions? Which scenario do you prefer?",
            options: [
              { text: "A. Where is the restroom?", next: 'a1' },
              { text: "B. Where is the meeting room?", next: 'b1' }
            ]
          },
          a1: { npc: "Excuse me, where is the restroom?",     expected: "Go straight ahead.",                 next: 'a2' },
          a2: { npc: "And then?",                              expected: "Turn left at the corner.",           next: 'a3' },
          a3: { npc: "Is it on the left or right?",            expected: "It's on your right.",                next: 'a4' },
          a4: { npc: "Is it next to anything?",                expected: "It's next to the cafeteria.",        next: 'a5' },
          a5: { npc: "How far is it?",                         expected: "Walk for two blocks.",               next: 'a6' },
          a6: { npc: "Do I turn at the traffic light?",        expected: "Turn right at the traffic light.",   next: 'a7' },
          a7: { npc: "Which floor is it on?",                  expected: "It's on the second floor.",          next: 'a8' },
          a8: { npc: "Will I find it easily?",                 expected: "Yes, you can't miss it.",            next: 'a9' },
          a9: { npc: "Got it, thanks!",                        expected: "Thank you so much.",                 next: 'aend' },
          aend: { npc: "You're welcome! 🎉", end: true },
          b1: { npc: "Excuse me, how do I get to the office?", expected: "Go straight ahead.",                 next: 'b2' },
          b2: { npc: "Do I turn left or right?",               expected: "Turn right at the traffic light.",   next: 'b3' },
          b3: { npc: "Where is it exactly?",                   expected: "It's next to the cafeteria.",        next: 'b4' },
          b4: { npc: "How many blocks?",                       expected: "Walk for two blocks.",               next: 'b5' },
          b5: { npc: "Is it on the left or right?",            expected: "It's on your left.",                 next: 'b6' },
          b6: { npc: "Which floor?",                           expected: "It's on the second floor.",          next: 'b7' },
          b7: { npc: "Will I find it?",                        expected: "Yes, you can't miss it.",            next: 'b8' },
          b8: { npc: "How do I ask if I get lost?",            expected: "Excuse me, where is the restroom?",  next: 'b9' },
          b9: { npc: "Thank you for your help!",               expected: "Thank you so much.",                 next: 'bend' },
          bend: { npc: "You're very helpful! 🎉", end: true }
        }
      },
      // 16 道章测题：与练习题无完全重复
      exam: [
        { id: 'e1',  type: 'choice', prompt: '"我怎么去办公室" 怎么问？', options: ["How do I get to the office?", "How to office?", "Where office?"], answer: 0, knowledge: '问路句型' },
        { id: 'e2',  type: 'choice', prompt: '"在红绿灯右转" 怎么说？', options: ['Turn right at the traffic light.', 'Right turn traffic light.', 'Turn right traffic light.'], answer: 0, knowledge: '祈使句' },
        { id: 'e3',  type: 'choice', prompt: '"在二楼" 怎么说？', options: ["It's on the second floor.", "It's on second floor.", "It's in second floor."], answer: 0, knowledge: '方位词' },
        { id: 'e4',  type: 'choice', prompt: 'Go ___ ahead.', options: ['straight', 'straightly', 'straights'], answer: 0, knowledge: '祈使句' },
        { id: 'e5',  type: 'fill',   prompt: 'Turn right ___ the traffic light.（填介词）', answer: 'at', accept: ['at'], knowledge: '介词 at' },
        { id: 'e6',  type: 'fill',   prompt: "It's on your ___.（填「左边」）", answer: 'left', accept: ['left'], knowledge: '方位词' },
        { id: 'e7',  type: 'fill',   prompt: "It's ___ to the cafeteria.（填「紧邻」）", answer: 'next', accept: ['next'], knowledge: '介词 to' },
        { id: 'e8',  type: 'fill',   prompt: 'Walk ___ two blocks.（填介词）', answer: 'for', accept: ['for'], knowledge: '介词 for' },
        { id: 'e9',  type: 'order',  prompt: '排列成句', words: ['Go', 'straight', 'ahead'], answer: ['Go', 'straight', 'ahead'], knowledge: '祈使句' },
        { id: 'e10', type: 'order',  prompt: '排列成句', words: ['It', 'is', 'on', 'your', 'right'], answer: ['It', 'is', 'on', 'your', 'right'], knowledge: '方位词' },
        { id: 'e11', type: 'translation', prompt: '中译英：打扰一下。', answer: 'Excuse me', accept: ['Excuse me'], knowledge: '交际用语' },
        { id: 'e12', type: 'translation', prompt: '中译英：在拐角左转。', answer: 'Turn left at the corner', accept: ['Turn left at the corner'], knowledge: '祈使句' },
        { id: 'e13', type: 'translation', prompt: '中译英：你不会错过的。', answer: "You can't miss it", accept: ["You can't miss it"], knowledge: '指路用语' },
        { id: 'e14', type: 'retell', prompt: 'Go straight ahead and turn left.', keywords: ['straight', 'turn', 'left'], knowledge: '祈使句' },
        { id: 'e15', type: 'retell', prompt: 'Turn left at the corner.', keywords: ['turn', 'left', 'corner'], knowledge: '祈使句' },
        { id: 'e16', type: 'retell', prompt: 'Walk for two blocks.', keywords: ['walk', 'two', 'blocks'], knowledge: '指路用语' }
      ],
      xp: 110
    },

    // ---------- 占位章节（默认锁定，解锁逻辑可演示） ----------
    { id: 'ch4', title: '代码评审',     emoji: '🔍', placeholder: true },
    { id: 'ch5', title: '技术面试',     emoji: '🎯', placeholder: true }
  ];

  // ---------- 徽章定义 ----------
  // check(s) 返回 true 时发放；s 为 state，含 xp/streak/completed/badges/
  // todayStudyMs/lastStudyDate/shadowCount/roleplayCount 等字段
  const BADGES = [
    { id: 'first_step',     name: '初学',       emoji: '🌱', desc: '获得第一点经验',         check: s => s.xp > 0 },
    { id: 'first_checkin', name: '首次打卡',   emoji: '📅', desc: '完成第一次每日打卡',     check: s => !!s.lastCheckIn },
    { id: 'streak7',        name: '坚持一周',   emoji: '🔥', desc: '连续打卡 7 天',          check: s => s.streak >= 7 },
    { id: 'ch1_done',       name: '自我介绍',   emoji: '👋', desc: '完成第一章',             check: s => !!s.completed.ch1 },
    { id: 'first_shadow',  name: '开口跟读',   emoji: '🎤', desc: '完成第一次跟读',         check: s => (s.shadowCount || 0) > 0 },
    { id: 'first_roleplay', name: '角色扮演',   emoji: '🎭', desc: '完成第一次角色扮演',     check: s => (s.roleplayCount || 0) > 0 },
    { id: 'xp100',          name: '百经验',     emoji: '💯', desc: '累计 100 XP',            check: s => s.xp >= 100 },
    { id: 'perfect',        name: '满分',       emoji: '🏆', desc: '章测全对一次',           check: s => Object.values(s.completed).some(c => c && c.examScore === 1) },
    { id: 'a1_done',        name: 'A1 毕业',    emoji: '🎓', desc: '完成前三章（A1）',       check: s => ['ch1', 'ch2', 'ch3'].every(id => s.completed[id]) }
  ];

  // ---------- 内置词典（约 500 个计算机高频词） ----------
  // 字幕点词查询：键为小写英文单词，值为中文释义
  const GLOSSARY = {
    // ---- 基础通用词汇（含 ch1/ch2/ch3 字幕用词） ----
    "hi": '嗨，问候语',
    "hello": '你好',
    "hey": '嘿，打招呼',
    "good": '好的',
    "morning": '早上 / 早晨',
    "afternoon": '下午',
    "evening": '傍晚',
    "night": '夜晚',
    "team": '团队',
    "meeting": '会议',
    "stand-up": '站会',
    "stand": '站立 / 忍受',
    "up": '向上',
    "down": '向下',
    "now": '现在',
    "today": '今天',
    "tomorrow": '明天',
    "yesterday": '昨天',
    "time": '时间',
    "second": '秒 / 第二',
    "minute": '分钟',
    "minutes": '分钟',
    "hour": '小时',
    "day": '天',
    "week": '周',
    "month": '月',
    "year": '年',
    "o'clock": '...点（钟）',
    "ten": '十',
    "nine": '九',
    "three": '三',
    "five": '五',
    "tasks": '任务',
    "task": '任务',
    "excuse": '原谅 / 劳驾',
    "me": '我',
    "where": '哪里',
    "restroom": '洗手间',
    "go": '去',
    "straight": '一直 / 笔直',
    "ahead": '向前',
    "turn": '转弯',
    "left": '左',
    "right": '右',
    "at": '在（地点/时间）',
    "the": '这 / 那个',
    "corner": '角落',
    "your": '你的',
    "on": '在...上',
    "how": '怎么 / 如何',
    "do": '做 / 助动词',
    "i": '我',
    "get": '得到 / 到达',
    "to": '到 / 对',
    "office": '办公室',
    "thank": '感谢',
    "you": '你',
    "much": '很多',
    "so": '如此 / 那么',
    "i'm": '我是',
    "am": '是（be 动词，第一人称）',
    "is": '是（be 动词，第三人称单数）',
    "are": '是（be 动词，复数/第二人称）',
    "be": '是',
    "a": '一个',
    "an": '一个',
    "developer": '开发者',
    "frontend": '前端',
    "backend": '后端',
    "fullstack": '全栈',
    "engineer": '工程师',
    "responsible": '负责的',
    "for": '为了 / 对于',
    "ui": '用户界面',
    "ux": '用户体验',
    "graduated": '毕业（过去式）',
    "from": '从 / 来自',
    "peking": '北京',
    "university": '大学',
    "nice": '美好的 / 高兴的',
    "meet": '遇见',
    "work": '工作',
    "as": '作为',
    "she": '她',
    "he": '他',
    "it": '它',
    "we": '我们',
    "they": '他们',
    "designer": '设计师',
    "let's": '让我们',
    "us": '我们',
    "finish": '完成',
    "please": '请',
    "wait": '等待',
    "starts": '开始（第三人称单数）',
    "start": '开始',
    "have": '有',
    "has": '有（第三人称单数）',
    "fixed": '修复（过去式）',
    "fix": '修复',
    "bug": '缺陷 / Bug',

    // ---- 编程语言与语法 ----
    "code": '代码',
    "coding": '编码',
    "program": '程序 / 编程',
    "programmer": '程序员',
    "programming": '编程',
    "language": '语言',
    "javascript": 'JavaScript 语言',
    "js": 'JavaScript 简称',
    "python": 'Python 语言',
    "java": 'Java 语言',
    "c": 'C 语言',
    "cpp": 'C++ 语言',
    "go": 'Go 语言',
    "rust": 'Rust 语言',
    "ruby": 'Ruby 语言',
    "php": 'PHP 语言',
    "swift": 'Swift 语言',
    "kotlin": 'Kotlin 语言',
    "typescript": 'TypeScript 语言',
    "ts": 'TypeScript 简称',
    "html": 'HTML 标记语言',
    "css": 'CSS 样式表',
    "sql": 'SQL 查询语言',
    "syntax": '语法',
    "statement": '语句',
    "expression": '表达式',
    "variable": '变量',
    "var": '变量关键字',
    "let": 'let 声明',
    "const": '常量声明',
    "constant": '常量',
    "function": '函数',
    "func": '函数简称',
    "method": '方法',
    "parameter": '形参',
    "argument": '实参',
    "param": '参数简称',
    "args": '参数简称',
    "return": '返回',
    "callback": '回调',
    "promise": 'Promise 异步对象',
    "async": '异步',
    "await": '等待异步结果',
    "sync": '同步',
    "class": '类',
    "object": '对象',
    "instance": '实例',
    "prototype": '原型',
    "inheritance": '继承',
    "polymorphism": '多态',
    "encapsulation": '封装',
    "abstract": '抽象的',
    "interface": '接口',
    "implements": '实现',
    "extends": '继承/扩展',
    "module": '模块',
    "import": '导入',
    "export": '导出',
    "require": '引入（CommonJS）',
    "library": '库',
    "lib": '库简称',
    "framework": '框架',
    "package": '包',
    "dependency": '依赖',
    "dependencies": '依赖',
    "version": '版本',
    "release": '发布',
    "deploy": '部署',
    "compile": '编译',
    "build": '构建',
    "runtime": '运行时',

    // ---- 数据结构 / 算法 ----
    "data": '数据',
    "structure": '结构',
    "array": '数组',
    "list": '列表',
    "linked": '链接的',
    "node": '节点',
    "stack": '栈',
    "queue": '队列',
    "deque": '双端队列',
    "tree": '树',
    "graph": '图',
    "hash": '哈希',
    "map": '映射 / Map 对象',
    "set": '集合',
    "dictionary": '字典',
    "object": '对象',
    "string": '字符串',
    "str": '字符串简称',
    "number": '数字',
    "num": '数字简称',
    "boolean": '布尔',
    "bool": '布尔简称',
    "null": '空值 null',
    "undefined": '未定义',
    "void": '空 / 无返回',
    "integer": '整数',
    "int": '整数简称',
    "float": '浮点数',
    "double": '双精度浮点',
    "char": '字符',
    "byte": '字节',
    "bit": '比特 / 位',
    "algorithm": '算法',
    "search": '搜索',
    "find": '查找',
    "sort": '排序',
    "sorted": '已排序',
    "merge": '合并',
    "split": '分割',
    "reverse": '反转',
    "swap": '交换',
    "loop": '循环',
    "for": 'for 循环',
    "while": 'while 循环',
    "iterate": '迭代',
    "iteration": '迭代',
    "recursion": '递归',
    "recursive": '递归的',
    "traverse": '遍历',
    "compare": '比较',
    "count": '计数',
    "index": '索引',
    "key": '键',
    "value": '值',
    "pair": '对',
    "entry": '条目',

    // ---- Web 与网络 ----
    "web": 'Web / 网络',
    "browser": '浏览器',
    "server": '服务器',
    "client": '客户端',
    "request": '请求',
    "response": '响应',
    "http": 'HTTP 协议',
    "https": 'HTTPS 协议',
    "url": '统一资源定位符',
    "uri": '统一资源标识符',
    "api": '应用程序接口',
    "rest": 'REST 架构风格',
    "restful": 'RESTful 风格',
    "endpoint": '接口端点',
    "route": '路由',
    "router": '路由器 / 路由组件',
    "json": 'JSON 数据格式',
    "xml": 'XML 标记语言',
    "yaml": 'YAML 格式',
    "ajax": 'AJAX 异步请求',
    "fetch": 'fetch 请求 API',
    "axios": 'Axios 库',
    "dom": '文档对象模型',
    "element": '元素',
    "tag": '标签',
    "attribute": '属性',
    "attr": '属性简称',
    "property": '属性',
    "props": 'props 属性',
    "selector": '选择器',
    "event": '事件',
    "listener": '监听器',
    "handler": '处理器',
    "trigger": '触发',
    "click": '点击',
    "input": '输入',
    "output": '输出',
    "submit": '提交',
    "form": '表单',
    "button": '按钮',
    "image": '图片',
    "img": '图片简称',
    "video": '视频',
    "audio": '音频',
    "canvas": 'Canvas 画布',
    "svg": 'SVG 矢量图',
    "cookie": 'Cookie',
    "session": '会话',
    "token": '令牌',
    "jwt": 'JWT 令牌',
    "auth": '认证简称',
    "login": '登录',
    "logout": '登出',
    "sign": '签名',
    "password": '密码',
    "user": '用户',
    "name": '名字',
    "email": '邮箱',
    "profile": '资料',

    // ---- 前端框架与生态 ----
    "react": 'React 框架',
    "vue": 'Vue 框架',
    "angular": 'Angular 框架',
    "svelte": 'Svelte 框架',
    "component": '组件',
    "components": '组件',
    "state": '状态',
    "props": '属性',
    "hook": 'Hook',
    "effect": '副作用',
    "render": '渲染',
    "mount": '挂载',
    "unmount": '卸载',
    "lifecycle": '生命周期',
    "context": '上下文',
    "store": '状态仓库',
    "redux": 'Redux 状态库',
    "vuex": 'Vuex 状态库',
    "pinia": 'Pinia 状态库',
    "router": '路由',
    "scaffold": '脚手架',
    "webpack": 'Webpack 打包工具',
    "vite": 'Vite 构建工具',
    "rollup": 'Rollup 打包工具',
    "esbuild": 'esbuild 打包工具',
    "babel": 'Babel 转译器',
    "eslint": 'ESLint 检查器',
    "prettier": 'Prettier 格式化',
    "jest": 'Jest 测试框架',
    "mocha": 'Mocha 测试框架',
    "cypress": 'Cypress E2E 测试',
    "playwright": 'Playwright 测试',
    "vitest": 'Vitest 测试',

    // ---- 后端与数据库 ----
    "database": '数据库',
    "db": '数据库简称',
    "table": '表',
    "row": '行',
    "column": '列',
    "field": '字段',
    "record": '记录',
    "schema": '模式 / 结构',
    "query": '查询',
    "insert": '插入',
    "update": '更新',
    "delete": '删除',
    "select": '查询',
    "join": '连接',
    "index": '索引',
    "primary": '主键',
    "foreign": '外键',
    "unique": '唯一',
    "constraint": '约束',
    "transaction": '事务',
    "commit": '提交事务',
    "rollback": '回滚',
    "migrate": '迁移',
    "migration": '迁移',
    "mysql": 'MySQL 数据库',
    "postgres": 'PostgreSQL 数据库',
    "mongodb": 'MongoDB 数据库',
    "redis": 'Redis 缓存',
    "sqlite": 'SQLite 数据库',
    "elasticsearch": 'ES 搜索引擎',
    "kafka": 'Kafka 消息队列',
    "rabbitmq": 'RabbitMQ 消息队列',
    "grpc": 'gRPC 框架',
    "websocket": 'WebSocket 协议',
    "socket": '套接字',
    "port": '端口',
    "host": '主机',
    "domain": '域名',
    "dns": '域名解析',
    "proxy": '代理',
    "nginx": 'Nginx 服务器',
    "apache": 'Apache 服务器',
    "node": 'Node.js / 节点',
    "node.js": 'Node.js 运行时',
    "deno": 'Deno 运行时',
    "bun": 'Bun 运行时',
    "express": 'Express 框架',
    "koa": 'Koa 框架',
    "nest": 'NestJS 框架',
    "fastify": 'Fastify 框架',
    "spring": 'Spring 框架',
    "django": 'Django 框架',
    "flask": 'Flask 框架',
    "rails": 'Rails 框架',
    "laravel": 'Laravel 框架',

    // ---- DevOps / 工具链 / 流程 ----
    "git": 'Git 版本控制',
    "github": 'GitHub 平台',
    "gitlab": 'GitLab 平台',
    "bitbucket": 'Bitbucket 平台',
    "commit": '提交',
    "push": '推送',
    "pull": '拉取',
    "fetch": '获取',
    "branch": '分支',
    "merge": '合并',
    "rebase": '变基',
    "clone": '克隆',
    "fork": '派生 / Fork',
    "pull": '拉取',
    "request": '请求',
    "pr": 'Pull Request 简称',
    "mr": 'Merge Request 简称',
    "issue": '议题 / Issue',
    "ticket": '工单',
    "milestone": '里程碑',
    "release": '发布',
    "tag": '标签',
    "version": '版本',
    "changelog": '更新日志',
    "ci": '持续集成',
    "cd": '持续交付/部署',
    "pipeline": '流水线',
    "jenkins": 'Jenkins CI 工具',
    "circle": 'CircleCI',
    "actions": 'GitHub Actions',
    "docker": 'Docker 容器',
    "container": '容器',
    "image": '镜像 / 图片',
    "kubernetes": 'Kubernetes 编排',
    "k8s": 'K8s 简称',
    "pod": 'Pod',
    "cluster": '集群',
    "namespace": '命名空间',
    "helm": 'Helm 包管理',
    "terraform": 'Terraform IaC',
    "ansible": 'Ansible 自动化',
    "aws": 'AWS 云',
    "gcp": '谷歌云',
    "azure": '微软云',
    "cloud": '云',
    "serverless": '无服务器',
    "lambda": 'Lambda 函数计算',
    "cdn": '内容分发网络',
    "cache": '缓存',
    "cached": '已缓存',
    "queue": '队列',
    "worker": '工作进程',
    "job": '作业',
    "task": '任务',
    "schedule": '调度 / 排程',
    "cron": 'Cron 定时',
    "log": '日志',
    "logs": '日志',
    "logging": '日志记录',
    "metric": '指标',
    "monitor": '监控',
    "alert": '告警',
    "trace": '追踪',
    "debug": '调试',
    "debugger": '调试器',
    "breakpoint": '断点',
    "profile": '性能分析',
    "memory": '内存',
    "cpu": 'CPU',
    "gpu": 'GPU',
    "disk": '磁盘',
    "memory": '内存',
    "process": '进程',
    "thread": '线程',
    "concurrent": '并发的',
    "concurrency": '并发',
    "parallel": '并行的',
    "async": '异步',
    "lock": '锁',
    "deadlock": '死锁',
    "race": '竞争',
    "thread-safe": '线程安全的',

    // ---- 测试与质量 ----
    "test": '测试',
    "testing": '测试',
    "unit": '单元',
    "integration": '集成',
    "e2e": '端到端',
    "mock": '模拟',
    "stub": '桩',
    "spy": '间谍函数',
    "fake": '伪造',
    "coverage": '覆盖率',
    "assert": '断言',
    "expect": '期望',
    "describe": '描述（测试套件）',
    "it": '它（测试用例）',
    "fixture": '测试夹具',
    "snapshot": '快照',
    "regression": '回归',
    "smoke": '冒烟',
    "lint": '静态检查',
    "type": '类型',
    "typing": '类型标注',
    "types": '类型',
    "generic": '泛型',
    "generics": '泛型',
    "any": '任意类型',
    "unknown": '未知类型',
    "never": '永不',
    "tuple": '元组',

    // ---- 设计模式 / 架构 ----
    "design": '设计',
    "pattern": '模式',
    "singleton": '单例',
    "factory": '工厂',
    "builder": '建造者',
    "observer": '观察者',
    "subscribe": '订阅',
    "subscription": '订阅',
    "publish": '发布',
    "pub": '发布简称',
    "sub": '订阅简称',
    "middleware": '中间件',
    "pipeline": '流水线',
    "layer": '层',
    "tier": '层',
    "monolith": '单体',
    "monolithic": '单体的',
    "microservice": '微服务',
    "microservices": '微服务',
    "soa": '面向服务架构',
    "api": '接口',
    "gateway": '网关',
    "bff": 'BFF 中间层',
    "cdn": '内容分发网络',
    "scale": '扩缩容',
    "scaling": '扩缩容',
    "horizontal": '水平的',
    "vertical": '垂直的',
    "shard": '分片',
    "sharding": '分片',
    "replica": '副本',
    "replication": '复制',
    "backup": '备份',
    "snapshot": '快照',
    "restore": '恢复',
    "retry": '重试',
    "fallback": '兜底',
    "circuit": '熔断',
    "breaker": '熔断器',
    "limit": '限流',
    "rate": '速率',
    "throttle": '节流',
    "debounce": '防抖',
    "queue": '队列',
    "buffer": '缓冲',
    "stream": '流',
    "flow": '流程',
    "batch": '批',

    // ---- 通用动词 / 形容词 ----
    "add": '添加',
    "remove": '移除',
    "delete": '删除',
    "update": '更新',
    "create": '创建',
    "make": '制作',
    "build": '构建',
    "run": '运行',
    "stop": '停止',
    "pause": '暂停',
    "resume": '恢复',
    "open": '打开',
    "close": '关闭',
    "save": '保存',
    "load": '加载',
    "read": '读取',
    "write": '写入',
    "send": '发送',
    "receive": '接收',
    "connect": '连接',
    "disconnect": '断开',
    "login": '登录',
    "logout": '登出',
    "register": '注册',
    "sign-up": '注册',
    "submit": '提交',
    "cancel": '取消',
    "confirm": '确认',
    "approve": '批准',
    "reject": '拒绝',
    "merge": '合并',
    "split": '分割',
    "copy": '复制',
    "paste": '粘贴',
    "cut": '剪切',
    "undo": '撤销',
    "redo": '重做',
    "refresh": '刷新',
    "reload": '重新加载',
    "reset": '重置',
    "restart": '重启',
    "boot": '启动',
    "reboot": '重启',
    "install": '安装',
    "uninstall": '卸载',
    "setup": '设置',
    "config": '配置简称',
    "configuration": '配置',
    "settings": '设置',
    "preference": '偏好',
    "option": '选项',
    "options": '选项',
    "default": '默认',
    "custom": '自定义',
    "advanced": '高级',
    "basic": '基础',
    "standard": '标准',
    "free": '免费 / 空闲',
    "paid": '付费',
    "premium": '高级版',
    "pro": '专业版',
    "lite": '精简版',
    "beta": '测试版',
    "alpha": '内测版',
    "stable": '稳定版',
    "latest": '最新',
    "old": '旧的',
    "new": '新的',
    "next": '下一个',
    "prev": '上一个',
    "previous": '上一个',
    "first": '第一',
    "last": '最后',
    "begin": '开始',
    "end": '结束',
    "middle": '中间',
    "top": '顶部',
    "bottom": '底部',
    "center": '中心',
    "left": '左',
    "right": '右',
    "up": '上',
    "down": '下',
    "inside": '内部',
    "outside": '外部',
    "above": '上方',
    "below": '下方',
    "next": '下一个',
    "previous": '上一个',
    "current": '当前',
    "previous": '上一个',
    "all": '全部',
    "any": '任意',
    "some": '某些',
    "none": '无',
    "each": '每个',
    "every": '每个',
    "both": '两者',
    "either": '任一',
    "neither": '两者都不',
    "true": '真',
    "false": '假',
    "yes": '是',
    "no": '否',
    "ok": '好的',
    "okay": '好的',
    "success": '成功',
    "fail": '失败',
    "error": '错误',
    "warning": '警告',
    "info": '信息',
    "fatal": '致命',
    "exception": '异常',
    "throw": '抛出',
    "catch": '捕获',
    "try": '尝试',
    "finally": '最终',
    "raise": '抛出',
    "assert": '断言',
    "reject": '拒绝',
    "resolve": '解决 / 完成',
    "fulfilled": '已成功',
    "pending": '待定',
    "rejected": '已失败',
    "loading": '加载中',
    "loaded": '已加载',
    "empty": '空',
    "null": '空值',
    "void": '空',
    "blank": '空白',
    "full": '满',
    "complete": '完成',
    "completed": '已完成',
    "incomplete": '未完成',
    "active": '激活 / 活跃',
    "inactive": '未激活',
    "enabled": '已启用',
    "disabled": '已禁用',
    "visible": '可见',
    "hidden": '隐藏',
    "show": '显示',
    "hide": '隐藏',
    "expand": '展开',
    "collapse": '折叠',
    "minimize": '最小化',
    "maximize": '最大化',
    "restore": '恢复',
    "zoom": '缩放',
    "in": '放大',
    "out": '缩小',
    "drag": '拖拽',
    "drop": '拖放',
    "click": '点击',
    "double": '双击',
    "tap": '轻点',
    "swipe": '滑动',
    "scroll": '滚动',
    "hover": '悬停',
    "focus": '聚焦',
    "blur": '失焦',
    "select": '选择',
    "selected": '已选中',
    "deselect": '取消选中',
    "highlight": '高亮',
    "mark": '标记',
    "unmark": '取消标记',
    "flag": '标志',
    "tag": '标签',
    "label": '标签',
    "badge": '徽章',
    "icon": '图标',
    "emoji": '表情',
    "image": '图片',
    "picture": '图片',
    "photo": '照片',
    "video": '视频',
    "audio": '音频',
    "text": '文本',
    "title": '标题',
    "subtitle": '副标题 / 字幕',
    "caption": '说明文字',
    "description": '描述',
    "summary": '摘要',
    "detail": '细节',
    "details": '详情',
    "note": '备注',
    "todo": '待办',
    "task": '任务',
    "list": '列表',
    "table": '表格',
    "grid": '网格',
    "tree": '树',
    "chart": '图表',
    "graph": '图 / 图表',
    "plot": '图表',
    "axis": '坐标轴',
    "legend": '图例',
    "tooltip": '提示框',
    "popup": '弹窗',
    "modal": '模态框',
    "dialog": '对话框',
    "alert": '告警框',
    "confirm": '确认框',
    "prompt": '输入框',
    "toast": '吐司提示',
    "notification": '通知',
    "message": '消息',
    "send": '发送',
    "receive": '接收',
    "reply": '回复',
    "forward": '转发',
    "share": '分享',
    "like": '点赞',
    "favorite": '收藏',
    "bookmark": '书签',
    "follow": '关注',
    "unfollow": '取消关注',
    "block": '屏蔽',
    "report": '举报',
    "feedback": '反馈',
    "review": '评审',
    "comment": '评论',
    "discuss": '讨论',
    "discussion": '讨论',
    "thread": '主题帖',
    "topic": '话题',
    "tag": '标签',
    "category": '分类',
    "section": '分区',
    "group": '分组',
    "team": '团队',
    "member": '成员',
    "user": '用户',
    "admin": '管理员',
    "owner": '所有者',
    "author": '作者',
    "editor": '编辑者',
    "viewer": '浏览者',
    "guest": '访客',
    "role": '角色',
    "permission": '权限',
    "permission": '权限',
    "access": '访问',
    "allow": '允许',
    "deny": '拒绝',
    "grant": '授予',
    "revoke": '撤销',
    "limit": '限制',
    "quota": '配额',
    "rate": '速率',
    "speed": '速度',
    "fast": '快',
    "slow": '慢',
    "quick": '快速',
    "rapid": '迅速',
    "delay": '延迟',
    "latency": '延迟',
    "throughput": '吞吐量',
    "bandwidth": '带宽',
    "size": '大小',
    "length": '长度',
    "width": '宽度',
    "height": '高度',
    "depth": '深度',
    "area": '区域',
    "volume": '体积',
    "weight": '权重',
    "mass": '质量',
    "time": '时间',
    "date": '日期',
    "year": '年',
    "month": '月',
    "week": '周',
    "day": '天',
    "hour": '小时',
    "minute": '分钟',
    "second": '秒',
    "ms": '毫秒',
    "us": '微秒',
    "ns": '纳秒',
    "past": '过去',
    "present": '现在',
    "future": '未来',
    "early": '早',
    "late": '晚',
    "before": '之前',
    "after": '之后',
    "since": '自从',
    "until": '直到',
    "while": '当...时',
    "during": '在...期间',
    "begin": '开始',
    "start": '开始',
    "end": '结束',
    "finish": '完成',
    "continue": '继续',
    "pause": '暂停',
    "resume": '恢复',
    "stop": '停止',
    "quit": '退出',
    "exit": '退出',
    "close": '关闭',
    "open": '打开',
    "enter": '进入',
    "return": '返回',
    "go": '去',
    "come": '来',
    "arrive": '到达',
    "leave": '离开',
    "stay": '停留',
    "move": '移动',
    "walk": '走',
    "run": '跑',
    "fly": '飞',
    "swim": '游',
    "drive": '驾驶',
    "ride": '骑',
    "stop": '停',
    "start": '启动',
    "restart": '重启',
    "boot": '开机',
    "shut": '关',
    "shutdown": '关机',
    "sleep": '休眠',
    "wake": '唤醒',
    "lock": '锁定',
    "unlock": '解锁',
    "encrypt": '加密',
    "decrypt": '解密',
    "hash": '哈希',
    "salt": '盐值',
    "sign": '签名',
    "verify": '验证',
    "auth": '认证',
    "authn": '认证',
    "authz": '授权',
    "authorize": '授权',
    "permit": '许可',
    "forbid": '禁止',
    "ban": '封禁',
    "kick": '踢出',
    "mute": '禁言',
    "report": '举报',
    "flag": '标记',
    "approve": '批准',
    "reject": '拒绝',
    "accept": '接受',
    "decline": '婉拒',
    "ignore": '忽略',
    "skip": '跳过',
    "pause": '暂停',
    "continue": '继续',
    "retry": '重试',
    "redo": '重做',
    "undo": '撤销',
    "revert": '还原',
    "restore": '恢复',
    "reset": '重置',
    "clear": '清除',
    "clean": '清理',
    "purge": '清空',
    "flush": '刷新',
    "refresh": '刷新',
    "reload": '重新加载',
    "rebuild": '重新构建',
    "reinstall": '重新安装',
    "reboot": '重启',
    "restart": '重启',
    "recompile": '重新编译',
    "refactor": '重构',
    "optimize": '优化',
    "improve": '改进',
    "enhance": '增强',
    "upgrade": '升级',
    "downgrade": '降级',
    "migrate": '迁移',
    "port": '移植 / 端口',
    "convert": '转换',
    "transform": '变换',
    "translate": '翻译',
    "parse": '解析',
    "serialize": '序列化',
    "deserialize": '反序列化',
    "encode": '编码',
    "decode": '解码',
    "compress": '压缩',
    "decompress": '解压',
    "zip": '压缩',
    "unzip": '解压',
    "archive": '归档',
    "extract": '解压',
    "package": '打包',
    "unpack": '解包',
    "bundle": '捆绑',
    "unbundle": '拆分',
    "minify": '压缩代码',
    "uglify": '混淆',
    "obfuscate": '混淆',
    "lint": '静态检查',
    "format": '格式化',
    "prettify": '美化',
    "beautify": '美化',
    "indent": '缩进',
    "align": '对齐',
    "wrap": '换行 / 包裹',
    "unwrap": '解包',
    "trim": '去除空白',
    "split": '分割',
    "join": '连接',
    "slice": '切片',
    "splice": '拼接',
    "concat": '拼接',
    "replace": '替换',
    "search": '搜索',
    "find": '查找',
    "filter": '过滤',
    "map": '映射',
    "reduce": '归约',
    "iterate": '迭代',
    "loop": '循环',
    "repeat": '重复',
    "recurse": '递归',
    "return": '返回',
    "yield": '产出',
    "emit": '发出',
    "listen": '监听',
    "subscribe": '订阅',
    "publish": '发布',
    "notify": '通知',
    "broadcast": '广播',
    "emit": '触发',
    "trigger": '触发',
    "fire": '触发',
    "invoke": '调用',
    "call": '调用',
    "apply": '应用',
    "bind": '绑定',
    "unbind": '解绑',
    "attach": '附加',
    "detach": '分离',
    "connect": '连接',
    "disconnect": '断开',
    "link": '链接',
    "unlink": '解除链接',
    "associate": '关联',
    "dissociate": '解除关联',
    "relate": '相关',
    "correlate": '相关',
    "compare": '比较',
    "contrast": '对比',
    "match": '匹配',
    "mismatch": '不匹配',
    "equal": '相等',
    "unequal": '不等',
    "same": '相同',
    "different": '不同',
    "similar": '相似',
    "identical": '完全相同',
    "unique": '唯一',
    "duplicate": '重复',
    "copy": '副本',
    "clone": '克隆',
    "original": '原始',
    "source": '源',
    "target": '目标',
    "destination": '目的地',
    "origin": '来源',
    "endpoint": '端点',
    "entry": '入口',
    "exit": '出口',
    "input": '输入',
    "output": '输出',
    "stdin": '标准输入',
    "stdout": '标准输出',
    "stderr": '标准错误',
    "stream": '流',
    "pipe": '管道',
    "channel": '通道',
    "queue": '队列',
    "stack": '栈',
    "buffer": '缓冲区',
    "cache": '缓存',
    "pool": '池',
    "bucket": '桶',
    "slot": '槽',
    "cell": '单元格',
    "row": '行',
    "column": '列',
    "grid": '网格',
    "matrix": '矩阵',
    "vector": '向量',
    "scalar": '标量',
    "tensor": '张量',
    "dimension": '维度',
    "shape": '形状',
    "size": '大小',
    "count": '数量',
    "total": '总计',
    "sum": '总和',
    "avg": '平均',
    "average": '平均',
    "mean": '均值',
    "median": '中位数',
    "mode": '众数',
    "max": '最大',
    "min": '最小',
    "limit": '限制',
    "offset": '偏移',
    "page": '页',
    "paginate": '分页',
    "cursor": '游标',
    "index": '索引',
    "key": '键',
    "value": '值',
    "pair": '键值对',
    "map": '映射',
    "set": '集合',
    "list": '列表',
    "array": '数组',
    "tuple": '元组',
    "record": '记录',
    "object": '对象',
    "struct": '结构体',
    "class": '类',
    "instance": '实例',
    "type": '类型',
    "primitive": '原始类型',
    "reference": '引用',
    "pointer": '指针',
    "address": '地址',
    "memory": '内存',
    "heap": '堆',
    "stack": '栈',
    "queue": '队列',
    "garbage": '垃圾',
    "gc": '垃圾回收',
    "collect": '收集',
    "allocate": '分配',
    "free": '释放',
    "leak": '泄漏',
    "overflow": '溢出',
    "underflow": '下溢',
    "exception": '异常',
    "error": '错误',
    "warning": '警告',
    "fatal": '致命',
    "crash": '崩溃',
    "hang": '卡死',
    "freeze": '冻结',
    "lag": '卡顿',
    "jank": '掉帧',
    "fps": '帧率',
    "memory": '内存',
    "cpu": 'CPU',
    "gpu": 'GPU',
    "disk": '磁盘',
    "network": '网络',
    "io": '输入输出',
    "disk": '硬盘',
    "ram": '内存',
    "rom": '只读存储器',
    "ssd": '固态硬盘',
    "hdd": '机械硬盘',
    "cloud": '云',
    "edge": '边缘',
    "iot": '物联网',
    "embedded": '嵌入式',
    "firmware": '固件',
    "hardware": '硬件',
    "software": '软件',
    "os": '操作系统',
    "kernel": '内核',
    "shell": '壳',
    "terminal": '终端',
    "console": '控制台',
    "cli": '命令行界面',
    "gui": '图形界面',
    "ide": '集成开发环境',
    "editor": '编辑器',
    "vscode": 'VS Code',
    "vim": 'Vim 编辑器',
    "emacs": 'Emacs 编辑器',
    "sublime": 'Sublime 编辑器',
    "jetbrains": 'JetBrains IDE',
    "intellij": 'IntelliJ IDEA',
    "pycharm": 'PyCharm',
    "webstorm": 'WebStorm',
    "eclipse": 'Eclipse IDE',
    "visual": 'Visual',
    "studio": 'Studio',
    "xcode": 'Xcode',
    "android": 'Android',
    "ios": 'iOS',
    "macos": 'macOS',
    "windows": 'Windows',
    "linux": 'Linux',
    "ubuntu": 'Ubuntu',
    "debian": 'Debian',
    "centos": 'CentOS',
    "fedora": 'Fedora',
    "alpine": 'Alpine',
    "unix": 'Unix',
    "bash": 'Bash',
    "zsh": 'Zsh',
    "powershell": 'PowerShell',
    "script": '脚本',
    "shell": 'Shell 脚本',
    "bat": '批处理',
    "sh": 'Shell 脚本',
    "command": '命令',
    "cmd": '命令简称',
    "arg": '参数',
    "flag": '标志',
    "option": '选项',
    "param": '参数',
    "env": '环境',
    "var": '变量',
    "config": '配置',
    "yaml": 'YAML',
    "toml": 'TOML',
    "ini": 'INI',
    "xml": 'XML',
    "json": 'JSON',
    "csv": 'CSV',
    "tsv": 'TSV',
    "md": 'Markdown',
    "markdown": 'Markdown',
    "html": 'HTML',
    "css": 'CSS',
    "js": 'JavaScript',
    "ts": 'TypeScript',
    "sql": 'SQL',
    "noql": 'NoSQL',
    "graphql": 'GraphQL',
    "protobuf": 'Protocol Buffers',
    "thrift": 'Thrift',
    "avro": 'Avro',
    "swagger": 'Swagger',
    "openapi": 'OpenAPI',
    "postman": 'Postman',
    "curl": 'curl 工具',
    "wget": 'wget 工具',
    "ssh": 'SSH',
    "telnet": 'Telnet',
    "ftp": 'FTP',
    "scp": 'SCP',
    "rsync": 'rsync',
    "tar": 'tar 归档',
    "gzip": 'gzip 压缩',
    "zip": 'zip 压缩',
    "bzip": 'bzip2 压缩',
    "7z": '7-Zip',
    "rar": 'RAR',
    "pdf": 'PDF',
    "doc": 'Word 文档',
    "xls": 'Excel 表格',
    "ppt": 'PowerPoint',
    "png": 'PNG 图片',
    "jpg": 'JPG 图片',
    "jpeg": 'JPEG 图片',
    "gif": 'GIF 图片',
    "svg": 'SVG 矢量图',
    "webp": 'WebP 图片',
    "ico": '图标文件',
    "mp4": 'MP4 视频',
    "mp3": 'MP3 音频',
    "wav": 'WAV 音频',
    "ogg": 'OGG 音频',
    "flac": 'FLAC 音频',
    "mkv": 'MKV 视频',
    "avi": 'AVI 视频',
    "mov": 'MOV 视频',
    "vtt": 'WebVTT 字幕',
    "srt": 'SRT 字幕',
    "ass": 'ASS 字幕',
    "ttf": 'TrueType 字体',
    "otf": 'OpenType 字体',
    "woff": 'WOFF 字体',
    "eot": 'EOT 字体'
  };

  // ---------- 暴露 ----------
  window.ENG_DATA = { CHAPTERS, BADGES, GLOSSARY };
  // 同时挂一份到 window.CHAPTERS 便于旧引用兼容
  window.CHAPTERS = CHAPTERS;
})();
